defaults:
  - trainer: default
  - models: m2m100
  - tokenizers: m2m100
  - dataloader: default
  - datasets: config
  - collators: default
  - earlystopping: default
  - checkpoint: default
  - loggers: wandb
  - optim: default
  - lr_monitor: default
do_train: False
do_test: True
inference_only: true
experiment_type: baseline
output_file: mnli_baseline_translation_m2m100_418M.txt
checkpoint_file: outputs/m2m100-base_baseline/checkpoints/model-epoch=5-val_loss=0.08-val_bleu=16.53.ckpt